image: docker:latest

build:
  script:
      - cd eos/Docker
      - cp ../genesis.json .
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build --rm -t $CI_REGISTRY_IMAGE .
      - docker push $CI_REGISTRY_IMAGE
