version: "3"

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data-volume:/data/db

  enunoded:
    image: enumivo/enumivo:latest
    command: /opt/enumivo/bin/enunoded.sh --data-dir /opt/enumivo/bin/data-dir --delete-all-blocks #--mongodb-uri mongodb://mongo:27017/ENU
    hostname: enunoded
    links:
      - mongo
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - enunode-data-volume:/opt/enumivo/bin/data-dir

  enuwallet:
    image: enumivo/enumivo:latest
    command: /opt/enumivo/bin/enuwallet --wallet-dir /opt/enumivo/bin/data-dir --http-server-address=127.0.0.1:8900
    hostname: enuwallet
    links:
      - enunoded
    volumes:
      - enuwallet-data-volume:/opt/enumivo/bin/data-dir

volumes:
 mongo-data-volume:
   external: true
 enunode-data-volume:
   external: true
 enuwallet-data-volume:
   external: true
