version: "3"

services:
  builder:
    build:
      context: builder
    image: enumivo/builder

  enunoded:
    build:
      context: .
    image: enumivo/enumivo
    command: /opt/enumivo/bin/enunoded.sh --data-dir /opt/enumivo/bin/data-dir
    hostname: enunoded
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - enunode-data-volume:/opt/enumivo/bin/data-dir

  enuwallet:
    image: enumivo/enu
    command: /opt/enumivo/bin/enuwallet --wallet-dir /opt/enumivo/bin/data-dir
    hostname: enuwallet
    links:
      - enunoded
    volumes:
      - enuwallet-data-volume:/opt/enumivo/bin/data-dir

volumes:
  enunode-data-volume:
    external: true
  enuwallet-data-volume:
    external: true
